### PR TITLE
String interpolation support

### PR DESCRIPTION
**Pull request by julienrf**

### CODE REVIEW

**Comment by julienrf** [comment]
I don’t understand what’s wrong with the build. Can anyone help me?

**Comment by julienrf** [comment]
It seems that I can not document the API addition because the `docs` project does not depend on the `api` project.

**Comment by jroper** [comment]
I think the problem is that travis is running two builds, one that builds the main project, the other that builds the docs project, the one that builds the docs project though isn't `publishLocal`ing the main project first, so it doesn't see the changes you've made.

**Comment by jroper** [comment]
Fixed in #87 - once that is merged, we can rerun this build.

**Comment by julienrf** [comment]
Thanks, now Travis is happy!

**Pull request merged**
