### PR TITLE
Change content type for JavaScript to application/json

### PR DESCRIPTION
**Pull request by samupra**

### CODE REVIEW

**Comment by samupra** [comment]
@gmethvin  Please let me know if there's something more I can do :)

**Comment by gmethvin** [comment]
@playframework/core I created a new branch for twirl 1.3.x since this is a potentially breaking change. We want the new Content-Type for json to be added in Play 2.7 / twirl 1.4.0.

**Comment by gpgekko** [comment]
Something went wrong here, since this change ended up in Play 2.6.12 / Twirl 1.3.14.
What is the reasoning behind changing this? It now differs from the definition of the Javascript content type used in the rest of Play, which seems rather odd.

**Comment by richdougherty** [comment]
Oops, it does look like (a) this change was included in the 1.3.x branch and (b) the 1.3.14 release was made from the master branch anyway.

Cc @gmethvin @marcospereira.

BTW I recently (#172) fixed up the 1.3.x branch to include all the 1.3.14 code, but this commit (ae99b3b) was already part of the 1.3.x branch prior to that PR.

**Comment by marcospereira** [comment]
@richdougherty I think it was added to 1.3.x unintentionally and should be reverted to avoid problems like @gpgekko described.

I will submit a PR reverting the commit, and the next release of Twirl should be made from 1.3.x branch to avoid new problems.

WDYT?

**Comment by marcospereira** [comment]
See #173.

**Comment by richdougherty** [comment]
@marcospereira I've now merged that change.

**Pull request merged**
