### PR TITLE
CI with GitHub Actions (using playframework/.github)

### PR DESCRIPTION
**Pull request by tototoshi**
This p-r is another version of https://github.com/playframework/twirl/pull/477 .

### CODE REVIEW

**Comment by mkurz** [comment]
Thanks @tototoshi!
I refactored the yml a bit and made sure it is up to date.

**Comment by mkurz** [comment]
Also @tototoshi I am going to merge that right now, please review anyway however and let me know if I am missing something. Thanks!

**Comment by mkurz** [comment]
Nice thing we now have snapshots published, so you can use them to try out the Scala 3 artifacts:
https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/ (grep for twirl)
You just need to add
```
resolvers += Resolver.sonatypeRepo("snapshots")
```

**Comment by tototoshi** [comment]
Thanks!

**Pull request merged**
