### PR TITLE
Upgrade to Interplay 1.2.0

### PR DESCRIPTION
**Pull request by wsargent**
Adds support for 2.12.0-M5

### CODE REVIEW

**Comment by schmitch** [comment]
strange build error. I couldn't reproduce it locally (on jdk 8) !? 
I would guess we also need:
```
addons:
  apt:
    packages:
      - oracle-java8-installer
```

**Comment by schmitch** [comment]
actually even interplay 1.1.0 fails. I mean we manually need to set `crossScalaVersions` on at least the `parser` and `compiler` since the plugin depends on it. but even that fails.
If I manually add `.settings(crossScalaVersions := List("2.11.7", "2.10.6", "2.12.0-M5"))` everywhere except the `plugin` the docs won't fail, however as soon as I raise the interplay project it fails, even when keeping `crossScalaVersions`, I even raised the doc `scalaVersion` to 2.11

**Comment by wsargent** [comment]
@schmitch welp.  https://github.com/playframework/playframework/blob/master/.travis.yml#L3

**Comment by schmitch** [comment]
will still fail. I tought that aswell but my hosts are at 101 and still failing :(

**Comment by schmitch** [comment]
Closed via https://github.com/playframework/twirl/commit/a4e1f69f4fc49fb1242cfdc6ca0313faf61418d0

**Pull request closed without merging**
