### PR TITLE
CompilerSpec: add test case for 'zipWithIndex'

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
ready for merge

**Comment by sullis** [comment]
@marcospereira

**Comment by sullis** [comment]
"zipWithIndex" is a real-world use case.  I have a large codebase of Twirl templates that use [zipWithIndex].  I am adding this test to the project because I want the test suite to reflect real-world usage.

**Comment by marcospereira** [comment]
My point here is that `zipWithIndex` is a method from Scala collections API, such as `map`, `takeWhile`, `fold`, etc. Why have a specific test for it?

**Comment by marcospereira** [comment]
Closing and reopening to trigger a new build.

**Pull request merged**
