### PR TITLE
sbt 1.7

### PR DESCRIPTION
**Pull request by mkurz**
@tototoshi @brbrown25 
So https://github.com/sbt/zinc/pull/1082 made it into sbt 1.7 (the pr also gets mentioned in the release notes: https://github.com/sbt/sbt/releases/tag/v1.7.0)
Do we need to change something?

### CODE REVIEW

**Comment by mkurz** [comment]
There is #506 already (opened by me :man_facepalming:)

**Comment by brbrown25** [comment]
> @tototoshi @brbrown25 So [sbt/zinc#1082](https://github.com/sbt/zinc/pull/1082) made it into sbt 1.7 (the pr also gets mentioned in the release notes: https://github.com/sbt/sbt/releases/tag/v1.7.0) Do we need to change something?

Hmm I feel like there was something in a tests but can't remember what was done. I'll try and look through and find it.

**Comment by mkurz** [comment]
@brbrown25 See #506 ...

**Comment by brbrown25** [comment]
So I think just merging #506 should do it

**Pull request closed without merging**
