### PR TITLE
compiler: account for Scala 2 and 3 differences in generated varargs code

### PR DESCRIPTION
**Pull request by ahjohannessen**
This adds a bit of redudant overloads. The most important aspect for me now is that mima and tests pass plus a minor release can be shipped. At a later time, one can remove overloads and duplication, do a cleanup with a breaking change and bump major version or similar.

### CODE REVIEW

**Comment by ihostage** [comment]
@ahjohannessen @mkurz I checked this for Gradle and as I expected all is fine. The changes in twirl-compiler works fine for all supported build systems.

**Comment by ahjohannessen** [comment]
@ihostage That is great to hear :)

**Review by mkurz — APPROVED** [review]
Thanks!

I pushed a commit which adds an overloaded function so we stay compatible with previous releases. I know the plugin project is not checked by MiMa because we ususally don't guarantee compatibility for sbt plugins, but this is a cheap thing to do and avoids breaking apps in case someone relies on the method.
I just used a dummy scala version that makes sure Scala 2 code gets generated by default, just like before.

I will cut a new release after that.

**Comment by mkurz** [comment]
@Mergifyio backport 1.6.x

**Comment by ahjohannessen** [comment]
@mkurz Super :) Next thing could perhaps be to introduce something like:

```scala
trait TwirlCompiler {
   def compile(…)
   // perhaps not necessary
   def compileVirtual(…)
}
```

and do some cleanup with compile options.

**Comment by mkurz** [comment]
@ahjohannessen Pull requests always welcome :wink:

**Pull request merged**
