### PR TITLE
Upgrade to sbt 1.3.0-RC1 and fix the scala-xml/classpath issue

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
```
[error] (plugin / update) sbt.librarymanagement.ResolveException: Error downloading org.scala-sbt:sbt:0.13.18
```

sbt 1.3 (via Coursier) can't find sbt 0.13?

**Comment by henricook** [comment]
Hmmm that's a weird error, i can't reproduce it locally - can you?

```
java -Xms2048M \
-Xmx2048M \
-Xss6M \ 
-XX:MaxPermSize=512M \
-jar \                                            
/home/henri/Downloads/sbt-1.3.0RC1/bin/sbt-launch.jar \
+publishLocal
```

**Comment by henricook** [comment]
Obviously we can fix this by adding `ThisBuild / useCoursier := false` to build.sbt

But i agree that's not ideal, it looks to me like Coursier's not respecting any resolver lists (I had a crack at plugins/built.sbt resolvers AND ~/.sbt/repositories) - at least for resolving this sbt jar? I'm a bit clueless as to why that may be

**Comment by bjaglin** [comment]
@henricook is the typesafe ivy resolver explicitly added? I ran into a similar problem when trying out 1.3.0-RC1, see https://github.com/sbt/sbt/issues/4698.

**Comment by henricook** [comment]
Thanks for the input @bjaglin - this was what i tried the other day, I checked out this branch by @dwijnand and then added:

```
resolvers += Resolver.typesafeRepo("releases")
resolvers += Resolver.typesafeIvyRepo("releases")
```

to the `plugins.sbt` and then tried to recreate the travis fail (and succeeded to recreate the failure) with:

```
java -Xms2048M \
-Xmx2048M \
-Xss6M \
-XX:MaxPermSize=512M \
-jar \
/home/henri/Downloads/sbt/bin/sbt-launch.jar \
"+publishLocal"
```

What's odd is that the error doesn't mention the typesafe repo:

```
[error] sbt.librarymanagement.ResolveException: Error downloading org.scala-sbt:sbt:0.13.18
[error]   Not found
[error]   not found: /home/henri/.ivy2/local/org.scala-sbt/sbt/0.13.18/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.18/sbt-0.13.18.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/sbt/0.13.18/sbt-0.13.18.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/sbt/0.13.18/sbt-0.13.18.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/sbt/0.13.18/ivys/ivy.xml
```

**Comment by henricook** [comment]
Woohoo, that was a good lead. I was adding the resolvers in `plugins.sbt` but then realised twirl builds as multiple projects. @dwijnand Do you mind amending your branch with this section of `build.sbt` replaced?

```
lazy val compiler = project
    .in(file("compiler"))
    .enablePlugins(PlayLibrary)
    .dependsOn(apiJvm, parser % "compile;test->test")
    .settings(commonSettings: _*)
    .settings(
      name := "twirl-compiler",
      libraryDependencies += scalaCompiler(scalaVersion.value),
      libraryDependencies ++= scalaParserCombinators(scalaVersion.value),
      fork in run := true,
      resolvers += Resolver.typesafeIvyRepo("releases")
    )
```

The key being the new `resolvers += ...` line

Once that line's added i get a clean `publishLocal`

**Comment by henricook** [comment]
@dwijnand I created a PR into your branch to make life easy: https://github.com/dwijnand/twirl/pull/1

**Comment by dwijnand** [comment]
Thanks for the PR, @henricook.  But before we go down that route I think it would be best to understand why that resolver is no longer available.

**Comment by henricook** [comment]
Fair enough, I may have to yield to someone who knows where to look for that one :joy:

**Comment by dwijnand** [comment]
I won't have a chance to get to this immediately.

**Pull request closed without merging**
