### PR TITLE
Add support for else if

### PR DESCRIPTION
**Pull request by tylersouthwick**
https://github.com/playframework/twirl/issues/33

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @tylersouthwick,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by tylersouthwick** [comment]
I signed the CLA

**Comment by schmitch** [comment]
LGTM

**Comment by mkurz** [comment]
@tylersouthwick Because it may is related and in case you have time - fixing  #80 would be nice too :smirk:

**Pull request merged**
