### PR TITLE
rename master to main, aligning with GitHub default

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
gah, this did not show up at https://travis-ci.com/github/playframework/twirl/pull_requests

**Comment by SethTisue** [comment]
merging anyway

**Comment by SethTisue** [comment]
branch renamed

**Comment by mkurz** [comment]
@SethTisue I think we should now completely remove the `master` branch.

**Comment by SethTisue** [comment]
@mkurz good catch -- done

**Pull request merged**
