### PR TITLE
Maven Support

### LINKED ISSUE #581: Maven Support
separated from #83. It's a part of https://github.com/playframework/play-meta/issues/8

### PR DESCRIPTION
**Pull request by alexmihailov**
Fixes #581

### CODE REVIEW

**Comment by ihostage** [comment]
Thanks, Alex @alexmihailov! I'll review this as soon as possible 😉

**Comment by mkurz** [comment]
@alexmihailov You need to run `sbt headerCreateAll` to pass the "code style" checks.

**Comment by alexmihailov** [comment]
Hi @ihostage! I implemented [sbt-maven-plugin-plugin](https://github.com/alexmihailov/sbt-maven-plugin-plugin) to create a maven plugin on sbt. I am rewrote twirl maven plugin. When the review is over, I will release the sbt-maven-plugin-plugin and remove the SNAPSHOT from plugins.sbt

**Comment by ihostage** [comment]
Depends on #676

**Comment by mkurz** [comment]
Will take a look now.

**Comment by ihostage** [comment]
@mkurz I think we are ready to merge it before final 2.0.0 😉

**Comment by mkurz** [comment]
I will not take time to deep dive into how everything works. I am sure you know what you are doing. For me it's important that the current twirl code does not get broken, this looks good. I may one day take the time to see how the sbt-maven-plugin etc. work, together with the code here.:+1: for adding the docs.

**Pull request merged**
