### PR TITLE
Fixing Travis scripts

### PR DESCRIPTION
**Pull request by renatocaval**

### CODE REVIEW

**Comment by dwijnand** [comment]
Don't `set -e`.  Trying to find how to source `travis_terminate`.

**Comment by ignasi35** [comment]
@renatocaval this is only a format away from complete :-)

**Comment by renatocaval** [comment]
> Don't set -e

@dwijnand, can you explain why? That's how we do in most of our builds.

**Comment by renatocaval** [comment]
If that's the reason http://mywiki.wooledge.org/BashFAQ/105, I still think for our case it's much simpler to use `set -e` then adding `|| exit 1` everywhere. 

Do you have any other reason for that?

**Comment by renatocaval** [comment]
Superseded by #293

**Pull request closed without merging**
