### PR TITLE
Support ECMAScript 6 Arrow Functions.

### PR DESCRIPTION
**Pull request by evanbennett**
Currently, a `case` statement (Scala or JavaScript) followed by an ES6 Arrow Function using `=> {` is parsed as a `caseExpression`. This also causes parsing errors if a brace exists in between.

To resolve this, I have:
* Removed `caseExpression` from `mixed`
* Created `atLeastOne` because a `matchblock` requires at least one `caseExpression`
* Created a `matchBlock` which requires only `caseExpression`s - I have created this by adding an argument to `block` to avoid code duplication
* Changed `matchExpOrSafeExpOrExpr` when it is a `match` to require a `matchBlock` instead of a `block`

This has the additional benefit or removing invalid parsing:
* Other options in `mixed` are invalid within a `matchBlock`
* `caseExpression`s are invalid outside a `matchBlock`

I have added test `caseAndArrowFunctions.scala.js` to cover the new behaviour, and `patternMatching` to make sure I did not break anything (other than the currently allowed invalid parsing listed above).

### CODE REVIEW

**Comment by marcospereira** [comment]
Thank you, @evanbennett.

Do you mind also adding tests to [`CompilerSpec`](https://github.com/playframework/twirl/blob/master/compiler/src/test/scala/play/twirl/compiler/test/CompilerSpec.scala)? It would be good to test compilation errors when the `match` is empty, when there is an invalid `mixed` there and also checking the `match` block is executing correctly.

**Comment by evanbennett** [comment]
I would have looked at updating other tests, but when I execute `test` in the `compiler` project, all the tests except `StringGrouper` fail with:
  scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.
  at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
  at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
  at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:48)
  at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
  at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:61)
  at scala.reflect.internal.Mirrors$RootsBase.getPackage(Mirrors.scala:172)
  at scala.reflect.internal.Mirrors$RootsBase.getRequiredPackage(Mirrors.scala:175)
  at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackage$lzycompute(Definitions.scala:183)
  at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackage(Definitions.scala:183)
  at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackageClass$lzycompute(Definitions.scala:184)
  ...

I am happy to add tests if I can fix this, but I have been unable to find a solution.

Also, some of the `TemplatePosition` tests in `sbt-twirl` fail due to Windows vs *nix path output. I skipped these as it seems most Play/twirl developers are not using Windows.

OS: Windows 10
Java: 
  java version "1.8.0_121"
  Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
  Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
sbt: 1.0.2

I have deleted all `target` folders within the project, but this has not fixed anything.

My other projects do not appear to effected by this.

**Comment by marcospereira** [comment]
Hi @evanbennett,

I was not able to reproduce the problem using sbt 1.0.4 and the following Java version:

```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```
By I'm able to reproduce it using sbt 1.0.4 **and** Java 9:
```
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```
When using Java 9, the following error occurs if I execute `sbt compiler/test`:

```
scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:48)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:61)
	at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:99)
	at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:102)
	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:264)
	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:264)
	at scala.reflect.internal.Definitions$DefinitionsClass.AnyRefClass$lzycompute(Definitions.scala:263)
	at scala.reflect.internal.Definitions$DefinitionsClass.AnyRefClass(Definitions.scala:263)
	at scala.reflect.internal.Definitions$DefinitionsClass.specialPolyClass(Definitions.scala:1120)
	at scala.reflect.internal.Definitions$DefinitionsClass.RepeatedParamClass$lzycompute(Definitions.scala:407)
	at scala.reflect.internal.Definitions$DefinitionsClass.RepeatedParamClass(Definitions.scala:407)
	at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses$lzycompute(Definitions.scala:1154)
	at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses(Definitions.scala:1152)
	at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode$lzycompute(Definitions.scala:1196)
	at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode(Definitions.scala:1196)
	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1261)
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1290)
	at sbt.compiler.Eval$$anon$1.<init>(Eval.scala:141)
	at sbt.compiler.Eval.run$lzycompute$1(Eval.scala:141)
	at sbt.compiler.Eval.run$1(Eval.scala:141)
	at sbt.compiler.Eval.unlinkAll$1(Eval.scala:144)
```
So, maybe you are somehow using Java 9? Is that error happening just for `compiler` project? Which sbt command are you executing? Do you have `JAVA_HOME` configured?

**Comment by evanbennett** [comment]
Hi @marcospereira,

So, maybe you are somehow using Java 9?
* I have not yet downloaded or installed Java 9.

Is that error happening just for compiler project?
* Yes.

Which sbt command are you executing?
* Either:
  * `test` or
  * `project compiler` and then `test`

Do you have JAVA_HOME configured?
* JAVA_HOME: C:\Program Files\Java\jdk1.8.0_152

I have uninstalled sbt and the JDK8, and reinstalled with the latest versions (1.0.4 and 1.8.0_152) and the error still occurs.

**Comment by evanbennett** [comment]
I have deleted my `~\.ivy2\cache` and `~\.ivy2\local` folders and republished everything as someone suggested the error my be caused by a corrupted jar.

The error still occurs.

**Comment by evanbennett** [comment]
Hi @marcospereira,

I have found the problem:
https://github.com/playframework/twirl/blob/72df96289f09cf306df19a0fc98b0ccbcb4bd2bc/compiler/src/test/scala/play/twirl/compiler/test/CompilerSpec.scala#L253 has `":"` which Windows needs as `";"` so it should be `File.pathSeparator` as used a few lines down.

I will work on the solution and the requested tests, and update the Pull Request.

**Comment by evanbennett** [comment]
I have add the Windows testing fix. I am now going to work on the requested additional tests.

**Comment by evanbennett** [comment]
@marcospereira 

CompileSpec.scala line 68-9: I expected either (3, 14) or (4, 1).
I cannot work out why this returns (3, 29)? The error is at the 29th non-line break character of the file?

**Comment by evanbennett** [comment]
Hi @marcospereira,

I have moved on to other things, but would still like this. Is it likely to progress?

**Pull request closed without merging**
